//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Staff
    {

        public int StaffID { get; set; }
        [Required(ErrorMessage = "{0} is required!")]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }
        
        [Display(Name = "Middle Name")]
        public string MiddleName { get; set; }

        [Required(ErrorMessage = "{0} is required!")]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        public string Gender { get; set; }

        [Required(ErrorMessage = "{0} is required!")]
        public string Position { get; set; }

        [Required(ErrorMessage = "{0} is required!")]
        [Display(Name = "Hired Date")]
        [DisplayFormat (DataFormatString =  "{0:d}")]
        public DateTime HiredDate { get; set; }
        public Nullable<decimal> Salary { get; set; }
    }
}
